### ISSUE TITLE
crates publishing teams

### ISSUE THREAD

**Issue by michaelkirk** [georust/robust#17]
👋 Hi @frewsxcv you are the only "user-owner" of the [robust crate on crates.io](https://crates.io/crates/robust), so only you can edit that crate's owners.

Following up on https://github.com/georust/meta/pull/21, I created a new [robust-publishers team](https://github.com/orgs/georust/teams/robust-publishers) for publishing to crates.io with you as the sole member and maintainer (actually since @frewsxcv is an organization owner, GH won't let me mark him as a maintainer, but it'd be redundant permissions anyway 🤷). 

Could you please [update the crate owners](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner)? Specifically:

---

- [ ] update **robust crate** owners on crates.io:

```
cd robust

# 💥 remove large publishing group
cargo owner --remove github:georust:core

# 🔐 add small publishing group
cargo owner --add github:georust:robust-publishers

# 🚨 You are currently the only user-owner of robust. 
# Consider adding another user-owner,  that way if for some reason you become inaccessible,
# we have someone else who can edit the owners. 
# See https://github.com/rust-lang/crates.io/issues/2906
cargo owner --add <username>

# make sure everything looks good 👀 
cargo owner --list
```
---

If there's anyone else you'd like to be able to publish the crates, feel free to add them to your publishing team, or as a user-owner. Consider that user-owners, as opposed to owners-via-team, can themselves edit the crate's owners, which could be desirable, or not, depending.

In particular, users who have been active in this repo in the past:
- @urschrei 
- @rmanoka 

 Are any of them interested in being added as publishers?

Let me know if you have any questions, or you can review https://github.com/georust/meta/pull/21.

**Comment by urschrei** [comment]
> Are any of them interested in being added as publishers?

Sure!

**Comment by frewsxcv** [comment]
done
